### ISSUE TITLE
How to calculate AOGM+ on deepcell dataset?

### ISSUE THREAD

**Issue by imzhangyd** [weigertlab/trackastra#11]
Thanks for your great work! There are some missing detections in deepcell dataset, which makes it impossible to construct a graph directly using traccuracy. So, how did you manage to construct the GT graph using GT detections?

**Comment by bentaculum** [comment]
Hi @imzhangyd,
I just went over the DeepCell test datasets I have on disk, with the main branch of `traccuracy`, and interestingly don't encounter this problem. All I get are warnings for non-connected objects.

Would you be able to provide more details?

Here are some pointers that come to mind:
- DeepCell requires some cropping to match images and masks match correctly.
- The benchmarks and metrics from the original DeepCell tracking paper might be helpful to you, as they were for me: https://github.com/vanvalenlab/Caliban-2023_Schwartz_et_al.
