### ISSUE TITLE
question about graph_to_ctc() input arguments

### ISSUE THREAD

**Issue by kevinyamauchi** [weigertlab/trackastra#13]
Hello! I am trying to prepare some data for training. My understanding is that the training data should be CTC-formatted. My current tracks are in a networkx `DiGraph`, so I thought I would use your [`graph_to_ctc()`](https://github.com/weigertlab/trackastra/blob/072ec7c213fd89518ac8c877a12b3130188614b8/trackastra/tracking/utils.py#L273) function to prepare the training data and I have a question about the input arguments. 

https://github.com/weigertlab/trackastra/blob/072ec7c213fd89518ac8c877a12b3130188614b8/trackastra/tracking/utils.py#L283-L284

- The `label` node attribute on the graph should be the label value in the segmentation provided in `masks_original`, right?
- It says the label values in `masks_original` should be "unique". Does this mean unique across the whole time series or just within a given frame?

Thanks!

**Comment by maweigert** [comment]
Hi @kevinyamauchi,

 > * The `label` node attribute on the graph should be the label value in the segmentation provided in `masks_original`, right?

Correct.

> * It says the label values in `masks_original` should be "unique". Does this mean unique across the whole time series or just within a given frame?

Only unique per frame, i.e. a "normal" label image

Hope that helps!

**Comment by kevinyamauchi** [comment]
Cool, I should be good to go then. Thanks for the quick reply!
