### ISSUE TITLE
Fusion events

### ISSUE THREAD

**Issue by Aseem139** [weigertlab/trackastra#15]
Can the tool detect fusion events between objects/cells ? Thank you for your time.

**Comment by bentaculum** [comment]
Hi @Aseem139 , our current implementation and public models do not. Would you like to model fusions and divisions, or fusions only?

**Comment by Aseem139** [comment]
So I am working with mitochondria that I have segmented and would like to track both fission and fusion events in. Thanks

**Comment by bentaculum** [comment]
Hi @Aseem139, for modelling fission and fusion jointly, one would have to take out the parental softmax normalization (training with `--causal_norm none`) and also adjust the linking (greedy or ILP) to additionally allow for fusions.
