### ISSUE TITLE
deepcell to ctc format

### ISSUE THREAD

**Issue by istan-ding** [weigertlab/trackastra#16]
Hi author! 
What is the deepcell format you use for this project? Is it the original .trks format? Or you convert it to ctc format? If so, I'll be appreciated if you can release the code that convert .trks to ctc format. Thank you!

**Comment by bentaculum** [comment]
Hi @istan-ding, the deepcell library comes with functions for conversion:
https://github.com/vanvalenlab/deepcell-tracking/blob/130bcd845cdf066e98baab80b5163bf86c3c346b/deepcell_tracking/isbi_utils.py#L40

https://github.com/vanvalenlab/Caliban-2024_Schwartz_et_al/blob/ee87df873b7e8cffa5c15b8b48ec7bd004e655c3/benchmarking/utils.py#L38C1-L54C94

**Comment by istan-ding** [comment]
> Hi @istan-ding, the deepcell library comes with functions for conversion: https://github.com/vanvalenlab/deepcell-tracking/blob/130bcd845cdf066e98baab80b5163bf86c3c346b/deepcell_tracking/isbi_utils.py#L40
> 
> https://github.com/vanvalenlab/Caliban-2024_Schwartz_et_al/blob/ee87df873b7e8cffa5c15b8b48ec7bd004e655c3/benchmarking/utils.py#L38C1-L54C94

Thank you for your help!
