### ISSUE TITLE
use_gt argument in the CTCData

### ISSUE THREAD

**Issue by kevinyamauchi** [weigertlab/trackastra#19]
Hello! I am trying to train `trackastra` with my own data and I was wondering what the [`use_gt` argument](https://github.com/weigertlab/trackastra/blob/34176bb00778de8163be9258ba4dff04927bbcbf/trackastra/data/data.py#L112) in the `CTCData` init method does. It see that it will look into the `01_ST/SEG` directory in the FLUO-N2DL-HeLa example folder (see screenshot below), but I'm not sure I understand what purpose it has in the training.

Looking at the CTC spec, it looks like it contains "silver truth" segmentations, but I'm not sure what I should put in there. Should I just copy the segmentations into that directory (using the same naming pattern as the TRA images)?

<img width="611" alt="Screenshot 2024-11-13 at 17 20 19" src="https://github.com/user-attachments/assets/9462e9f7-7b18-4ed7-b575-e5fc3860f6ad">

**Comment by bentaculum** [comment]
Hi @kevinyamauchi,
`use_gt=True` will use try to do a union of ST and GT masks for all masks available in the GT TRA folder. In CTC datasets, the GT TRA masks are sometimes only points/disks, while the ST SEG masks are dense instance segmentations.

If you don't have separate silver truth SEG masks, the dataloader will simply load the xx_GT/TRA folder.

Hope this helps.

**Comment by kevinyamauchi** [comment]
Thanks for the quick reply, @bentaculum !

Just to make sure I understand correctly, if I want to use the masks in `xx_GT/TRA`, I should set `use_gt=False`? Or do I set `use_gt=True` and when it doesn't find a `xx_ST/SEG` directory it falls back on just the masks in `xx_GT/TRA`?

**Comment by bentaculum** [comment]
For training please always use `use_gt=True`, which includes the fallback behaviour you describe. `use_gt=False` is legacy from when we used `CTCData` class also for prediction.

**Comment by kevinyamauchi** [comment]
Got it. Thank you!
