### ISSUE TITLE
No example data

### ISSUE THREAD

**Issue by ripaul** [weigertlab/trackastra#2]
Hi Ben & Martin!

Just installed your package using `pip` and tried to run your little demo script, both as described in the README, but seems like there were some changes, so guess it should be
```
from trackastra.data import example_data_bacteria
imgs, masks = example_data_bacteria()
```
in the README.

Moreover, it seems like the `trackastra/data/resources` folder isn't being installed via `pip`
```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
/tmp/ipykernel_1448584/2558804596.py in ?()
      5 from trackastra.tracking import graph_to_ctc, graph_to_napari_tracks
      6 from trackastra.data import example_data_bacteria
      7 
      8 # load some test data images and masks
----> 9 imgs, masks = example_data_bacteria()
...
FileNotFoundError: [Errno 2] No such file or directory: '/home/rpaul/proj/trackastra-playground/venv/lib/python3.10/site-packages/trackastra/data/resources/trpL_150310-11_img.tif'
```
I believe you might be missing a `MANIFEST.in` file to add non-code data to the installation, in case that's intended. If so, feel free to accept the pull request.

**Comment by bentaculum** [comment]
Hi Richi, thanks for your instant try of the repo :) Keep me posted how it's going.
