### ISSUE TITLE
Code for AOGM measurement

### ISSUE THREAD

**Issue by won5830** [weigertlab/trackastra#7]
Hi,
thank you for your great work ! 
Btw, could you share your code block or function for measuring AOGM score for predicted segmentation and graph ?

**Comment by bentaculum** [comment]
Hi @won5830, you can either use our python implementation [traccuracy](https://github.com/Janelia-Trackathon-2023/traccuracy) or the binaries provided by the Cell Tracking Challenge.

**Comment by won5830** [comment]
Thank you !
