### ISSUE TITLE
Are the track annotations of the bacterial dataset accurate?

### ISSUE THREAD

**Issue by imzhangyd** [weigertlab/trackastra#9]
I read in the original paper that the dataset was annotated using a segmentation tool called Schnitzcells 1.1. Are the results reliable? Have the annotations been manually calibrated? Please let me know if I misunderstood something. Thank you.

**Comment by maweigert** [comment]
Hi @imzhangyd 

The bacteria dataset of van Vliet et al 2018 was initially segmented and tracked with Schnitzcells, but then heavily manually curated and validated. 

Hope that helps
